### ISSUE TITLE
Unicode fix (UnicodeDecodeError: 'ascii' codec can't decode byte)

### ISSUE THREAD

**Issue by jquast** [noahspurrier/pexpect#3]
(see pull request #5 )

allow 'encoding' parameter to be used with the method .interact()

When unspecified, the systems preferred locale is used, such as 'utf8' or 'bige' or whatever your liking.

The underlying and related methods, such as output_filter= previously received raw bytestrings (type 'str').

I've decided that these will now receive unicode. This is desirable, and legacy code would have thrown a UnicodeDecodeError for any bytes outside of 'ascii', anyway, so are not likely to make use of non-ascii, which means existing code will most likely work.

A simple test that will succeed with this fix, run tests/interact.py, Input a utf-8 character, such as ƒ:

Traceback (most recent call last):
  File "tests/interact.py", line 23, in <module>
    p.interact()
  File "/Library/Python/2.7/site-packages/pexpect.py", line 1492, in interact
    self.__interact_copy(escape_character, input_filter, output_filter, encoding)
  File "/Library/Python/2.7/site-packages/pexpect.py", line 1526, in __interact_copy
    data.encode(encoding, 'replace'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 0: ordinal not in range(128)

**Comment by jquast** [comment]
a preview sample of what I have in mind, http://ascii.io/a/2879

**Comment by forivall** [comment]
Also, take a look at [takluyver/pexpect](https://bitbucket.org/takluyver/pexpect/overview), which is another unicode-compatible fork of pexpect.

**Comment by jquast** [comment]
takluyver really "imported" pexpect, that is, refactored a great deal, his intention was to do as the INSTALL is, to copy 'pexpect.py' to his local project.

Trying to bring in the intention though; which seems to be of adding encoding= parameter to pexpect.spawn() in addition to the pexpect.interact() method already completed.

**Comment by jquast** [comment]
This has been submitted as pull request #5, closing this issue #3, appreciate any feedback.

Jordan, is your need for unicode support something that is demonstrable?

**Comment by forivall** [comment]
@jquast No, I don't have any pressing need for unicode support.

Whenever I clone a git repo from github, I check to see if there are any forks that are more up to date than the original; I found both takluyver's fork and your fork.
